Tool-daruda/35-APPJAM-SERVER-DARUDA

src/main/java/com/daruda/darudaserver/global/image/entity/Image.java, src/main/java/com/daruda/darudaserver/global/image/imageController/imageController.java, src/main/java/com/daruda/darudaserver/global/image/service/ImageService.java, src/main/java/com/daruda/darudaserver/global/infra/S3/S3Service.java
- close #19
- 이미지 폴더 관련 로직 제거
- 이미지 엔티티 변경
- 이미지 업로드 및 삭제 테스트
을 첨부해주세요 -->
=> [Feat] 이미지 로직 수정

src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java, src/main/java/com/daruda/darudaserver/global/config/WebConfig.java
- close #24
- CORS 설정 변경
- S3 CORS 설정
- Security URL 수정
- 정적 변수는 대문자랑 '_' 로 써야해서 수정했어요!
- 줄 바꿈 수정 
- CORS 가 와일드 카드로 되어있는 부분 수정했어요. 보안 상의 이슈로! 그래도 미리 설정해놔서 몇가지만 빠구면 되어서 편했어요! 감사합니다
https://www.notion.so/Cors-36aff8d9d86748c5a370e7247c33e1f7?pvs=4
=> [Chore] CORS 수정

src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolListRes.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java, src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java, src/main/java/com/daruda/darudaserver/global/handler/ValidatorUtil.java
- close #10
- 툴 리스트 구현
- 무한 스크롤 구현
무한 스크롤 찾아보면서 QueryDSL , JPA 중 고민했는데. QueryDSL은 잘몰라서 일단 JPA 로 했고.
그리고 Page, Slice 두가지 선택지가 있었는데, Page 안에 Slice 가 있는 거여서, Page 써서 구현했습니다.
사실 무제한 스크롤을 처음 해봐서 이게 맞는 건지는 잘 모르겠는데... 나중에 클라라 이야기 해보고 필요시 수정할게요!
빠뜨린 Exception 이나, 다른 아이디어 있으면 말씀해주세요
=> [Feat] 툴 리스트 구현

build.gradle, src/main/java/com/daruda/darudaserver/domain/user/entity/UserEntity.java, src/main/java/com/daruda/darudaserver/global/auth/UserIdArgumentResolver.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/provider/JwtTokenProvider.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/auth/security/UserAuthentication.java
=> [fix] JWT 파싱 해결

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> [Fix] Refresh Token오류 해결

src/main/java/com/daruda/darudaserver/DarudaApplication.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolScrap.java, src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/dto/response/FavoriteToolsResponse.java, src/main/java/com/daruda/darudaserver/domain/user/dto/response/PagenationDto.java, src/main/java/com/daruda/darudaserver/domain/user/entity/UserEntity.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/config/PageableConfig.java
- close #43 
1. Request Parameter로 페이지 번호를 받습니다
2. UserId로 ToolScrap을 조회하여 얻은 ToolId를 Page객체로 받습니다
3. Dto로 매핑하여 응답을 패이지 정보(totalPage 수, 현재 페이지 번호, 한 페이지에 들어가는 size)를 반환해줍니다
UserId->ToolScrap ->ToolId -> Tool 이라서 어떻게 정렬을 해야할지 몰라서 아직 정렬(createdAt)은 안 되어있는 상태입니다
=> Feat/#43 관심있는 툴 조회API

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
- close #60
- getBoardId -> Id
=> [Fix] board Entity 변경에 따른 수정

src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/GetBoardResponse.java, src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #57 
- JPQL 수정
- Record 변경
- isFree 받도록 controller 수정
- 자유게시판 인지를 먼저 검사하기 떄문에 isFree 가 1 , toolId  =1 로 받아서 isFree 즉 자유게시판으로 생성된다
- isFree가 필수값!!
=> [Fix] 코리 반영 및 JPQL 수정

src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/GetBoardResponse.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/global/common/response/ScrollPaginationDto.java
- close #56 
- ScrollDTO 생성
- Board 조회 DTO 변경
=> [Feat] Scroll  DTO 생성

src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java, src/main/java/com/daruda/darudaserver/domain/comment/dto/response/GetCommentRetrieveResponse.java, src/main/java/com/daruda/darudaserver/domain/comment/repository/CommentRepository.java, src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java, src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
=> #61 [fix] 정렬 기준 추가

src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java, src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlatformRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolListRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreListRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDetailGetRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolListRes.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolResponse.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolScrapCount.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolScrapRes.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/Plan.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/RelatedTool.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java, src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/global/common/response/ScrollPaginationCollection.java, src/main/java/com/daruda/darudaserver/global/handler/ValidatorUtil.java, src/main/resources/application.yml
- close #65
- 우선 Builder 의 AccessLevel 때문에 DB에 직접 넣고 돌리는 과정에서 에러 발생해서 다 없앴어요
- 원래 인기순은 찜수*10 + viewCount 인데 툴의 모든 찜수를 Count 해서 가져오기 어렵고, 이걸 또 값을 저장하는건 아닌  것 같아서. 그냥 view 수 만으로 하자고 우길 예정
=> [Feat] 툴 무한 스크롤 구현

src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #75
- 삭제된 게시글이 조회되는 문제 발생
- 게시글 조회식 삭제된 게시글은 제외하고 조회할 수 있도록 수정
- 이미 삭제한 게시글일 경우에도 존재하지 않는 게시글 처리
=> [Fix] 삭제된 게시글 조회 수정

src/main/java/com/daruda/darudaserver/global/config/WebConfig.java
- close #79 
- 무한 로딩 해결 위한 설정 변경
=> [Fix] EC2 에러 해결

src/main/java/com/daruda/darudaserver/global/config/WebConfig.java, src/main/resources/application.yml
- close #79
데이터 베이스 RDS 연결
ddl-auto : update 변경
=> [Fix] database 설정 변경

.github/workflows/dev-CD.yml, docker-compose.yml
=> [CICD] yml 파일 수정 및 배포 스크립트 작성

src/main/java/com/daruda/darudaserver/global/config/CorsConfig.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> #103 [fix] CORS Security에 추가

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
=> #106 [fix] redirect 수정

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/dto/response/MyProfileResponse.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> Fix/#109 API 1차 오류 해결

src/main/java/com/daruda/darudaserver/domain/community/ValidateBoard.java, src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java, src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/dto/response/FavoriteBoardsResponse.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
- close #108
- 내가 쓴 게시글 조회 Scrap 여부 수정
- 내가 쓴 게시글, 수정한 게시글 Scrap 여부 수정
- 툴 스크랩 여부 수정
- 툴 관련해서 전체적으로 Scrap 여부 수정했어용 근테 틀릴 수도...하하ㅏ하
=> [Fix] 조회시 스크랩 여부 수정

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
=> #117 [fix] 카카오 redirect 변경

logs/logging.2025-01-21.0, src/main/resources/logback-spring.xml
- close #120 
- 로그 파일 수정
- 로그 파일 단계 수정
- secret 에는 안올려놨어요! ~~~
- /home/ubuntu 로 이동해요
=> [Fix] 로깅 파일 수정

src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java
- close #122
- 틀 플랜 Response 수정
- 살려주세영
=> [Fix] Tool 플랜 Response 수정

logs/logging.2025-01-21.0, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java, src/main/resources/logback-spring.xml
=> [CICD] 배포하기

src/main/resources/logback-spring.xml
=> #126 [fix] log 레벨 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #128 
1. 기존에는 이미지가 a628cbc9-fc53-424a-a8ad-e541d4653c13.jpg 형태로 왔던 것을 https://daruda.s3.ap-northeast-2.amazonaws.com/a628cbc9-fc53-424a-a8ad-e541d4653c13.jpg  형태로 변경해주었습니다
=> #128 [fix] 이미지 return 값 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #128
- 이미지 Return 값 수정
=> [Fix] 이미지 return 값 수정 (#129)

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
=> [CICD] 수정 후 배포

src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
=> [CICD] API 수정 배포

build.gradle, src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java, src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolResponse.java, src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/global/config/JpaConfig.java
- close #125
- 툴 리스트조회로직 수정
- 툴 리스트 dto 수정
- 툴 리스트 무료여부 필터링 수정
=> [Fix] 툴 리스트 조회 수정

src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java
- close #138 
카테고리에서 '/' -> '&'로 수정
=> #138 [fix] 카테고리 수정

src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java, src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java, src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
=> #138 [fix] 게시글 리스트 수정

src/main/generated/com/daruda/darudaserver/domain/tool/entity/QTool.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #143 
게시글 상세조회 response에서 toolId를 내려주도록 수정하였습니다
=> #143 [fix] 게시글조회 Response toolId 포함

src/main/generated/com/daruda/darudaserver/domain/tool/entity/QTool.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
* #143 [fix] 게시글조회 Response toolId 포함
* #143 [fix] getToolId 코드 간소화
* #143 [fix] QTool 살리기
- close #
=> [Fix] 게시글조회 Response toolId 포함 (#144)

src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java, src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java, src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
- close #147 
1. JWT Exception 세부화
2. 로깅 추가
3. Response Type 세부화
=> [Fix] 예외처리 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/community/util/ValidateBoard.java
- close #146
- 자유 게시글 이미지 로고만 수정했어요
=> [Fix] 자유 게시글 로고 이미지 수정

src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java, src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/community/util/ValidateBoard.java, src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
=> [Fix/#147] 예외처리 세부화

src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java, src/main/java/com/daruda/darudaserver/domain/community/dto/req/BoardCreateAndUpdateReq.java, src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
- close #149
- Board Create DTO 수정
- Spring Security 수정
=> [Fix] Board Response 수정

src/main/java/com/daruda/darudaserver/global/config/CorsConfig.java, src/main/java/com/daruda/darudaserver/global/config/WebConfig.java
=> [Fix] Config 수정

src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> [Fix] security 수정

src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> #157 [fix] security 수정 (#159)

src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
- close #161 
EXCLUDE_URL에 board 추가
=> #161 [fix] JwtAuthenticationFilter 수정

src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> #161 [fix] SecurityConfig 수정

src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
=> Security Config 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/java/com/daruda/darudaserver/global/config/CorsConfig.java, src/main/java/com/daruda/darudaserver/global/config/WebConfig.java
- close #158
- 게시글 리스트 수정 - 전체 게시글, 토큰 필요없이 가능, toolId 추가
- CORS 주소 추가
=> [Fix] CORS 추가 및 게시글 리스트 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #161 
JwtAuthentication 수정
=> #161 [fix] JwtAuthentication 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
=> #172 [fix] 게시글 스크랩 수정

src/main/java/com/daruda/darudaserver/domain/user/dto/response/LoginResponse.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
=> [Fix] 닉네임 Response 추가

src/main/java/com/daruda/darudaserver/domain/user/dto/response/LoginResponse.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
=> #173 [fix] nickName Response 추가 (#176)

src/main/java/com/daruda/darudaserver/domain/comment/entity/CommentEntity.java, src/main/java/com/daruda/darudaserver/domain/comment/repository/CommentRepository.java, src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java, src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
- close #184 
회원 탈퇴에서 댓글 삭제 추가
게시글과 연관되어있는 댓글도 함께 삭제
=> Fix/#185 API 5차 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
- close #189
- 툴 리스트 조회, 게시글 리스트 조회시 nextCursor 부터 시작 조회되도록 수정했어용
=> [Fix] 리스트 조회 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
=> [CICD] 리스트 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java, src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java, src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java, src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
=> [CICD] 도커 죽인다

src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
- close #192
- 툴리스트 조회 수정 - JPQL 썼는데 잘 모르고 쓰니 어려워서 걍 전부다 불러오는 로직으로 처리했어요. 임시 방편
=> [Fix] 툴 리스트 조회

src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
- close #197
툴 서비스 충돌 해결 및 재배포
=> [Fix] ToolService 수정

src/main/java/com/daruda/darudaserver/domain/community/service/BoardImageService.java
- close #181
- image Service URL 수정
=> [Fix] 이미지 URL 수정

src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java, src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
- close #205
- 게시글 삭제해도 내가 쓴 글에서 조회되는 현상 발생
- 게시글 삭제하면, Scrap 삭제하도록 수정
=> [Fix] 게시글 Scrap 조회 수정

.gitignore, src/main/resources/application.yml
- close #215 
1. yml 파일 환경변수 처리
2. 깃이그노어에서 yml 파일 제거
3. jwt 토큰 만료 기간 정상화
=> Fix/#215 토큰 만료 기간 변경

src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
=> #215 [fix] yml파일 환경변수 처리

src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
=> #215 [fix] 카카오 정보 log 찍기

src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
=> #215 [fix] redirectUri 명시

src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java, src/main/resources/application.yml
=> [CI/CD]외안되2

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/dto/request/AuthCodeRequest.java
- close #227 
1. @RequestHeader에서 @RequestBody로 변경
2. json 형식 명시
3. dto 생성
=> Fix/#227 인가코드 전송 변경

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/dto/request/AuthCodeRequest.java, src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
=> [CI/CD] 제발 돼라

src/main/java/com/daruda/darudaserver/global/config/CorsConfig.java
=> #227 [fix] Cors 추가

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
=> #227 [fix] RequestHeader 추가

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/resources/application.yml
=> [CI/CD] 이번에는..?

src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java, src/main/resources/application.yml
=> [CI/CD] 도커죽여

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
=> #236 [fix] controller 로직 수정

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
=> [CI/CD] 제발돼줘

src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java, src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
=> [CI/CD]부탁이야

src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java, src/main/resources/application.yml
=> [CI/CD]한번만

.github/workflows/ci.yml, src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java, src/main/resources/application-prod.yml
- close #255
- 비활성화 보다는 하향을 통해 로그를 볼 수 있도록 설정합니다.
=> #255 [Refactor] AccessToken 추출 실패 에러 로그 비활성화

build.gradle, config/naver-checkstyle-rules.xml, config/naver-checkstyle-suppressions.xml
- close #251 
- 빌드 과정에서 린터 적용 및 필요 파일 추가
=> #251 [Chore] 린터 파일 추가 및 gradle 설정
